export const Products = [
  {
    id: 1,
    image: "/product-1.jpg",
    name: "Product 1",
    productName: "Dove Sneakers",
    amount: "$107.99",
    rating: 4,
    label: "NEW",
  },
  {
    id: 2,
    image: "/product-2.jpg",
    name: "Product 2",
    productName: "Piqué Biker Jacket",
    amount: "$67.24",
    rating: 3,
    label: "",
  },
  {
    id: 3,
    image: "/product-10.jpg",
    name: "Product 3",
    productName: "ZVA 3-in-one Perfume",
    amount: "$40.41",
    rating: 5,
    label: "SALE",
  },
  {
    id: 4,
    image: "/product-13.jpg",
    name: "Product 4",
    productName: "Piqué Leather Bag",
    amount: "$70.32",
    rating: 4,
    label: "",
  },
  {
    id: 5,
    image: "/product-12.jpg",
    name: "Product 5",
    productName: "Green Camo Hoodie",
    amount: "$55.40",
    rating: 3,
    label: "",
  },
  {
    id: 6,
    image: "/product-5.jpg",
    name: "Product 6",
    productName: "T-shirt Contrast Pocket",
    amount: "$49.66",
    rating: 4,
    label: "SALE",
  },
  {
    id: 7,
    image: "/product-7.jpg",
    name: "Product 7",
    productName: "Zara Leather Backpack",
    amount: "$31.37",
    rating: 3,
    label: "",
  },
  {
    id: 8,
    image: "/product-8.jpg",
    name: "Product 8",
    productName: "ASOS Plain Tee",
    amount: "$26.28",
    rating: 4,
    label: "",
  },
];

export const CardIcons = [
  { id: 1, image: "/heart.png", name: "heart" },
  { id: 2, image: "/compare.png", name: "compare" },
  { id: 3, image: "/search.png", name: "search" },
];
