export const Products = [
  {
    id: 1,
    image: "/product-1.jpg",
    name: "Product 1",
    productName: "Dove Sneakers",
    amount: "$107.99",
    rating: 4,
    label: "NEW",
    oldPrice: "",
  },
  {
    id: 2,
    image: "/product-2.jpg",
    name: "Product 2",
    productName: "Piqué Biker Jacket",
    amount: "$67.24",
    rating: 3,
    label: "",
    oldPrice: "",
  },
  {
    id: 3,
    image: "/product-10.jpg",
    name: "Product 3",
    productName: "ZVA 3-in-one Perfume",
    amount: "$40.41",
    rating: 5,
    label: "SALE",
    oldPrice: "$59.99",
  },
  {
    id: 4,
    image: "/product-13.jpg",
    name: "Product 4",
    productName: "Piqué Leather Bag",
    amount: "$70.32",
    rating: 4,
    label: "",
    oldPrice: "",
  },
  {
    id: 5,
    image: "/product-12.jpg",
    name: "Product 5",
    productName: "Green Camo Hoodie",
    amount: "$55.40",
    rating: 3,
    label: "",
    oldPrice: "",
  },
  {
    id: 6,
    image: "/product-5.jpg",
    name: "Product 6",
    productName: "T-shirt Contrast Pocket",
    amount: "$49.66",
    rating: 4,
    label: "SALE",
    oldPrice: "$62.09",
  },
  {
    id: 7,
    image: "/product-7.jpg",
    name: "Product 7",
    productName: "Zara Leather Backpack",
    amount: "$31.37",
    rating: 3,
    label: "",
    oldPrice: "",
  },
  {
    id: 8,
    image: "/product-8.jpg",
    name: "Product 8",
    productName: "ASOS Plain Tee",
    amount: "$26.28",
    rating: 4,
    label: "",
    oldPrice: "",
  },
];

export const CardIcons = [
  { id: 1, image: "/heart.png", name: "heart" },
  { id: 2, image: "/compare.png", name: "compare" },
  { id: 3, image: "/search.png", name: "search" },
];

export const FooterShoppingList = [
  { id: 1, list: "Clothing Store" },
  { id: 2, list: "Trending Shoes" },
  { id: 3, list: "Accessories" },
  { id: 4, list: "Sale" },
];

export const FooterServiceList = [
  { id: 1, list: "Contact Us" },
  { id: 2, list: "Payment Method" },
  { id: 3, list: "Delivery Information" },
  { id: 4, list: "Return & Exchanges" },
];

export const SidebarList = [
  { id: 1, option: "Men" },
  { id: 2, option: "Women" },
  { id: 3, option: "Kids" },
  { id: 4, option: "Bags" },
  { id: 5, option: "Belts" },
  { id: 6, option: "Wallets" },
  { id: 7, option: "Watches" },
  { id: 8, option: "Accessories" },
  { id: 9, option: "Winter Wear" },
];

export const ColorList = [
  { id: 1, option: "Red", value: 10, background: "bg-red-500" },
  { id: 2, option: "Blue", value: 14, background: "bg-blue-500" },
  { id: 3, option: "Orange", value: 8, background: "bg-orange-500" },
  { id: 4, option: "Black", value: 12, background: "bg-black" },
  { id: 5, option: "Green", value: 9, background: "bg-green-500" },
  { id: 6, option: "Yellow", value: 2, background: "bg-yellow-500" },
];

export const SizeList = [
  { id: 1, option: "S", value: 6 },
  { id: 2, option: "M", value: 20 },
  { id: 3, option: "L", value: 7 },
  { id: 4, option: "XL", value: 16 },
  { id: 5, option: "XXL", value: 10 },
  { id: 6, option: "XXXL", value: 2 },
];

export const FilterOptions = [
  { id: 1, option: "Recommended" },
  { id: 2, option: "Most Popular" },
  { id: 3, option: "New Arrivals" },
  { id: 4, option: "Top Rated" },
  { id: 5, option: "Low to High" },
  { id: 6, option: "High to Low" },
];

export const FullProducts = [
  {
    id: 1,
    image: "/product-1.jpg",
    name: "Product 1",
    productName: "Dove Sneakers",
    amount: "$107.99",
    rating: 4,
    label: "NEW",
    oldPrice: "",
  },
  {
    id: 2,
    image: "/product-2.jpg",
    name: "Product 2",
    productName: "Piqué Biker Jacket",
    amount: "$67.24",
    rating: 3,
    label: "",
    oldPrice: "",
  },
  {
    id: 3,
    image: "/product-10.jpg",
    name: "Product 3",
    productName: "ZVA 3-in-one Perfume",
    amount: "$40.41",
    rating: 5,
    label: "SALE",
    oldPrice: "$59.99",
  },
  {
    id: 4,
    image: "/product-13.jpg",
    name: "Product 4",
    productName: "Piqué Leather Bag",
    amount: "$70.32",
    rating: 4,
    label: "",
    oldPrice: "",
  },
  {
    id: 5,
    image: "/product-12.jpg",
    name: "Product 5",
    productName: "Green Camo Hoodie",
    amount: "$55.40",
    rating: 3,
    label: "",
    oldPrice: "",
  },
  {
    id: 6,
    image: "/product-5.jpg",
    name: "Product 6",
    productName: "T-shirt Contrast Pocket",
    amount: "$49.66",
    rating: 4,
    label: "SALE",
    oldPrice: "$62.09",
  },
  {
    id: 7,
    image: "/product-7.jpg",
    name: "Product 7",
    productName: "Zara Leather Backpack",
    amount: "$31.37",
    rating: 3,
    label: "",
    oldPrice: "",
  },
  {
    id: 8,
    image: "/product-8.jpg",
    name: "Product 8",
    productName: "ASOS Plain Tee",
    amount: "$26.28",
    rating: 4,
    label: "",
    oldPrice: "45.88",
  },
  {
    id: 9,
    image: "/product-9.jpg",
    name: "Product 5",
    productName: "Balenciaga Embroided Tee",
    amount: "$55.40",
    rating: 3,
    label: "",
    oldPrice: "",
  },
  {
    id: 10,
    image: "/product-4.jpg",
    name: "Product 6",
    productName: "T-shirt Contrast Pocket",
    amount: "$49.66",
    rating: 4,
    label: "",
    oldPrice: "$62.09",
  },
  {
    id: 11,
    image: "/product-6.jpg",
    name: "Product 7",
    productName: "Adidas Shawl",
    amount: "$30.65",
    rating: 3,
    label: "SALE",
    oldPrice: "$99.55",
  },
  {
    id: 12,
    image: "/product-11.jpg",
    name: "Product 8",
    productName: "Dungree Multipurpose Backpack",
    amount: "$70.32",
    rating: 5,
    label: "NEW",
    oldPrice: "",
  },
];

export const ProductDetails = {
  id: 1,
  productName: "Hooded Thermal Anorak",
  image: "/product-big-1.png",
  rating: 5,
  newPrice: "$107.99",
  oldPrice: "$159.99",
  productDescription:
    "Coat with quilted lining and an adjustable hood. Featuring long sleeves with adjustable cuff tabs, adjustable asymmetric hem with elastic side tabs and a front zip fastening with placket.",
  redColor: "bg-red-500",
  blueColor: "bg-blue-500",
  orangeColor: "bg-orange-500",
  blackColor: "bg-black",
  greenColor: "bg-green-500",
  yellowColor: "bg-yellow-500",
  sizeS: "S",
  sizeM: "M",
  sizeL: "L",
  sizeXL: "XL",
  sizeXXL: "XXL",
  sizeXXXL: "XXXL",
};

export const SmallImageSizes = [
  { id: 1, image: "/thumb-1.png" },
  { id: 2, image: "/thumb-2.png" },
  { id: 3, image: "/thumb-3.png" },
  { id: 4, image: "/thumb-4.png" },
];

export const LargeImageSizes = [
  { id: 1, image: "/product-big-1.png" },
  { id: 2, image: "/product-big-2.png" },
  { id: 3, image: "/product-big-3.png" },
  { id: 4, image: "/product-big-2.png" },
];

// product details...
export const headings = ["Descriptions", "Additional Information", "Reviews"];
